name: Atividades práticas LinceTech Academy

# Accepts 'flutter' or 'dart'
type: dart

# Configuration for each step
steps:
  - name: Atividade 1
    directory: step_1
    has_solution: true
  - name: Atividade 2
    directory: step_2
    has_solution: true
  - name: Atividade 3
    directory: step_3
    has_solution: true
